import './globals.css'
import { Inter } from 'next/font/google'
import { TaskProvider } from '@/context/TasksContext'
import Link from 'next/link'
import Layout from '@/components/Layout'
import Navigation from '@/components/Navigation'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-teal-600'>

              
        <TaskProvider>
          <Navigation/> 
          <Layout>
            {children}
          </Layout>
        </TaskProvider>
               
          
      </body>
    </html>
  )
}
